/**
 * E-12 live glossary — parse the bible glossary section into terms at COMPILE time,
 * and emit the generated web module the GlossaryTerm tooltip consumes. Pure: no I/O
 * here (the compile script does the fs write). Term lines are `**Term** — definition`.
 */
export interface GlossaryTerm { term: string; definition: string }

const TERM_LINE = /^\*\*(.+?)\*\*\s*[—:-]\s*(.+)$/

export function extractGlossary(sectionMarkdown: string): GlossaryTerm[] {
  const terms: GlossaryTerm[] = []
  for (const raw of sectionMarkdown.split('\n')) {
    const m = TERM_LINE.exec(raw.trim())
    if (m) terms.push({ term: m[1].trim(), definition: m[2].trim() })
  }
  return terms
}

export function renderGlossaryModule(terms: GlossaryTerm[]): string {
  const sorted = [...terms].sort((a, b) => a.term.localeCompare(b.term))
  const entries = sorted.map(t => `  ${JSON.stringify(t.term)}: ${JSON.stringify(t.definition)},`).join('\n')
  return [
    '// GENERATED by `pnpm bible` from artifacts/bible/sections/14-glossary.md — do not edit by hand.',
    '// The glossary-sync test fails if this drifts from the section.',
    'export const GLOSSARY: Record<string, string> = {',
    entries,
    '}',
    '',
  ].join('\n')
}
